sudo: false
language: python
python:
    - '3.6'
    - '3.7'
    - '3.8'
#    - '3.9'
env:
    - ROOT_PATH=~/jasmin JASMIN_RELEASE=0.10.3
# Command to install dependencies
install:
    - pip install -r requirements.txt
# Commands to run tests:
script:
    # Pylint code analysis and rating:
    - ./misc/pylint/run.sh
    # Trial tests and coverage:
    - coverage run --source=jasmin -m twisted.trial tests
    - coveralls
    # Docs building test:
    - cd misc/doc;make html;cd ../../
    
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements:
    - pip install -r requirements-test.txt
    - chmod +x ./misc/pylint/run.sh
before_install:
    - virtualenv venv
    - source venv/bin/activate
    - mkdir -p $ROOT_PATH/var/log/jasmin
    - mkdir -p $ROOT_PATH/etc/init.d
    - ln -s `pwd`/misc/config $ROOT_PATH/etc/jasmin
    - chmod -R 777 $ROOT_PATH/var/log/jasmin $ROOT_PATH/etc/jasmin/store
addons:
  apt:
    packages:
    # jasmin installation requirement:
    # As documented here http://docs.jasminsms.com/en/latest/installation/index.html
    - python-dev
    - libffi-dev
    - libssl-dev
    - bc
    # Travis-ci migrated to Ubuntu Xenial as the default env.
    # As described here https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
    # Rabbitmq is no more provided out of the box, installed it manually:
    - rabbitmq-server
notifications:
  slack:
    secure: guCY7vL67vUhvNYLzInV/EIPMZ7ciq+/s0UlfmKvGYrjIMwXdgfshgKXdHF194eQ9+f0dF8ea1P1/aGqCE4Q4ULPZ555FbftNy/bVLfUPn01+odorAux3rVNq4ezX2QlQc06DpVS2r7U+grM+MQtNdRjoZIuAeipp3YRhyyuIr8=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ed32e6d5fb2778d9854
    on_success: change
    on_failure: always
    on_start: never
