sudo: false
language: python
python:
    - '2.7'
env:
    - ROOT_PATH=~/jasmin JASMIN_RELEASE=0.8b6
# Command to install dependencies
install:
    - python setup.py sdist
    - pip install "dist/jasmin-$JASMIN_RELEASE.tar.gz"
    - cp misc/config/init-script/jasmind-ubuntu $ROOT_PATH/etc/init.d/jasmind
# Commands to run tests:
script:
    # Trial tests and coverage:
    - coverage run `which trial` jasmin
    # Docs building test:
    - cd misc/doc;make html;cd ../../
    # Report coverage:
    - coverage report --omit=/usr/*,/home/travis/virtualenv/*,venv/*
    # Pylint code analysis and rating:
    - ./misc/pylint/run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements:
    - pip install -r test-requirements
    - chmod +x ./misc/pylint/run.sh
before_install:
    - virtualenv venv
    - source venv/bin/activate
    - mkdir -p $ROOT_PATH/var/log/jasmin
    - mkdir -p $ROOT_PATH/etc/jasmin/resource
    - mkdir -p $ROOT_PATH/etc/jasmin/init-script
    - mkdir -p $ROOT_PATH/etc/jasmin/store
    - mkdir -p $ROOT_PATH/etc/init.d
    - chmod -R 777 $ROOT_PATH/var/log/jasmin $ROOT_PATH/etc/jasmin/store
addons:
  apt:
    packages:
    # jasmin installation requirement:
    # As documented here http://docs.jasminsms.com/en/latest/installation/index.html
    - python-dev
    - libffi-dev
    - libssl-dev
    - bc
notifications:
    slack:
        secure: guCY7vL67vUhvNYLzInV/EIPMZ7ciq+/s0UlfmKvGYrjIMwXdgfshgKXdHF194eQ9+f0dF8ea1P1/aGqCE4Q4ULPZ555FbftNy/bVLfUPn01+odorAux3rVNq4ezX2QlQc06DpVS2r7U+grM+MQtNdRjoZIuAeipp3YRhyyuIr8=
