language: python
python:
    - "2.7"
# Command to install dependencies
install:
    - python setup.py sdist
    - sudo pip install dist/jasmin-0.6b0.tar.gz
# Commands to run tests:
script:
    # Add jasmind to system autostartup:
    - sudo update-rc.d jasmind defaults
    # Service startup test:
    - sudo /etc/init.d/jasmind start
    - sleep 2
    - sudo /etc/init.d/jasmind status
    # Stop service:
    - sudo /etc/init.d/jasmind stop
    # Cleaning before going for further tests:
    - sudo rm -f /var/log/jasmin/*;sudo rm -f /etc/jasmin/store/*
    # Trial tests and coverage:
    - sudo chmod -R 777 /var/log/jasmin /etc/jasmin/store
    - sudo coverage run `which trial` jasmin
    # Docs building test:
    - cd misc/doc;make html;cd ../../
    # Report coverage:
    - sudo coverage report --omit=/usr/*,/home/travis/virtualenv/*
    # Pylint code analysis and rating:
    - cd ./misc/pylint; sudo ./run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements:
    - sudo pip install -r test-requirements
    # pylint requirements:
    - sudo apt-get install -qq pylint bc
    - chmod +x ./misc/pylint/run.sh
before_install:
    - sudo apt-get update -qq
    # jasmin installation requirement:
    # As documented here http://docs.jasminsms.com/en/latest/installation/index.html
    - sudo apt-get install -qq python-dev libffi-dev libssl-dev
    - sudo useradd jasmin
    - sudo ln -s /etc/jasmin/init-script/jasmind /etc/init.d/
    - sudo mkdir -p /var/log/jasmin /etc/jasmin/resource /etc/jasmin/init-script /etc/jasmin/store /var/run/jasmin
    - sudo chown `whoami` /etc/jasmin /etc/jasmin/resource /etc/jasmin/init-script
    - sudo chown jasmin. /var/log/jasmin /etc/jasmin/store /var/run/jasmin
