language: python
python:
    - "2.7"
# Command to install dependencies
install:
    - python setup.py sdist
    - pip install dist/jasmin-0.5.1-beta.tar.gz
# Commands to run tests:
script:
    # Add jasmind to system autostartup
    - sudo update-rc.d jasmind defaults
    # Service startup test:
    - sudo /etc/init.d/jasmind start
    - sleep 2
    - sudo /etc/init.d/jasmind status
    # Stop service and status test
    - sudo /etc/init.d/jasmind stop
    - sleep 2
    - sudo /etc/init.d/jasmind status
    # Debugging
    - sudo tail -n 200 /var/log/syslog
    # Cleaning before going for further tests
    - sudo rm -f /var/log/jasmin/*;sudo rm -f /etc/jasmin/store/*
    # Trial tests and coverage:
    - sudo chmod -R 777 /var/log/jasmin /etc/jasmin/store
    - coverage run `which trial` jasmin
    # Docs building test:
    - cd misc/doc;make html;cd ../../
    # Report coverage:
    - coverage report --omit=/usr/*,/home/travis/virtualenv/*
    # Pylint code analysis and rating:
    - ./misc/pylint/run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements:
    - pip install -r test-requirements
    # pylint requirements:
    - sudo apt-get install -qq pylint bc
    - export PYLINTRC=./misc/pylint/pylintrc
    - chmod +x ./misc/pylint/run.sh
before_install:
    - sudo apt-get update -qq
    # jasmin requirement:
    - sudo apt-get install -qq python-dev libffi-dev libssl-dev
    - sudo useradd jasmin
    - sudo ln -s /etc/jasmin/init-script/jasmind /etc/init.d/
    - sudo mkdir -p /var/log/jasmin /etc/jasmin/resource /etc/jasmin/init-script /etc/jasmin/store /var/run/jasmin
    - sudo chown `whoami` /etc/jasmin /etc/jasmin/resource /etc/jasmin/init-script
    - sudo chown jasmin. /var/log/jasmin /etc/jasmin/store /var/run/jasmin
