sudo: false
language: python
python:
    - '2.7'
env:
    - ROOT_PATH=~/jasmin JASMIN_RELEASE=0.9.31
# Command to install dependencies
install:
    - python setup.py sdist
    - pip install "dist/jasmin-$JASMIN_RELEASE.tar.gz" --no-binary jasmin
# Commands to run tests:
script:
    # Trial tests and coverage:
    - coverage run `which trial` jasmin
    # Report coverage:
    - coverage report --include=venv/lib/python2.7/site-packages/jasmin/* --fail-under=80
    # Docs building test:
    - cd misc/doc;make html;cd ../../
    # Pylint code analysis and rating:
    - ./misc/pylint/run.sh
services:
    - rabbitmq
    - redis-server
before_script:
    # Test requirements:
    - pip install -r test-requirements
    - chmod +x ./misc/pylint/run.sh
before_install:
    - virtualenv venv
    - source venv/bin/activate
    - mkdir -p $ROOT_PATH/var/log/jasmin
    - ln -s `pwd`/jasmin/misc/config $ROOT_PATH/etc/jasmin
    - mkdir -p $ROOT_PATH/etc/init.d
    - chmod -R 777 $ROOT_PATH/var/log/jasmin $ROOT_PATH/etc/jasmin/store
addons:
  apt:
    packages:
    # jasmin installation requirement:
    # As documented here http://docs.jasminsms.com/en/latest/installation/index.html
    - python-dev
    - libffi-dev
    - libssl-dev
    - bc
notifications:
  slack:
    secure: guCY7vL67vUhvNYLzInV/EIPMZ7ciq+/s0UlfmKvGYrjIMwXdgfshgKXdHF194eQ9+f0dF8ea1P1/aGqCE4Q4ULPZ555FbftNy/bVLfUPn01+odorAux3rVNq4ezX2QlQc06DpVS2r7U+grM+MQtNdRjoZIuAeipp3YRhyyuIr8=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ed32e6d5fb2778d9854
    on_success: change
    on_failure: always
    on_start: never
