version: "3"

services:
  redis:
    image: redis:alpine

  rabbit-mq:
    image: rabbitmq:alpine
  jasmin:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: jasmin
    volumes:
      - ./jasmin:/usr/jasmin/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - redis
      - rabbit-mq
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq
      JCLI_BIND: 0.0.0.0
