apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  hostname: redis
  subdomain: store
  containers:
  - name: redis
    image: redis:6-alpine
    command:
      - redis-server
      - "/etc/redis/redis.conf"
    env:
    - name: MASTER
      value: "true"
    volumeMounts:
    - mountPath: /etc/redis/
      name: redisconfig
  volumes:
    - name: redisconfig
      configMap:
        name: etcredis
---
apiVersion: v1
kind: Service
metadata:
  name: store
spec:
  selector:
    name: redis
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcredis
data:
  redis.conf: ""
